### ISSUE TITLE
`java.lang.OutOfMemoryError: GC overhead limit exceeded` while convert epub to txt

### ISSUE THREAD

**Issue by xinbimingjingtai** [groupdocs-conversion/GroupDocs.Conversion-for-Java#57]
I' using `groupdocs-conversion` to convert epub to txt, I got a `java.lang.OutOfMemoryError: GC overhead limit exceeded`.
I tried modify vm options `-XX:-UseGCOverheadLimit`, `-Xmx`, `-XX:MaxPermSize`, `-XX:ReservedCodeCacheSize`, but it still occurred.

macOS Sonoma 14.6.1

java version "1.8.0_381"

Apache Maven 3.9.3

<dependency>
    <groupId>com.groupdocs</groupId>
    <artifactId>groupdocs-conversion</artifactId>
    <version>24.9</version>
</dependency>

```
    public static void main(String[] args) {
        Locale.setDefault(Locale.CHINA); // or Locale.US
        // Load the source eBook file
        try (Converter converter = new Converter("<epub file path>")) {
            ConvertOptions<?> options;
            options = new WordProcessingConvertOptions();
            options.setFormat(WordProcessingFileType.Txt);
            converter.convert("<txt target path>", options);
        }
    }
```

```
Exception in thread "java.lang.ThreadGroup[name=main,maxpri=10]_452" java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.groupdocs.conversion.internal.c.a.pd.internal.ms.System.Collections.Generic.lf.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.ms.System.Collections.Generic.lf.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.ms.System.Collections.Generic.lf.<init>(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l31y.l0p.<init>(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.dom.Element.<init>(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.HTMLElement.<init>(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.HTMLParagraphElement.<init>(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.dom.ld.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.lt.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.dom.lk.createElement(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39p.ld.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39p.ld.lf(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39u.lh.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39p.ld.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39p.ld.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39v.ly$1.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lt$1.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lt.lk(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lu.lf(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lb.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l39v.ly.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.html.dom.lk$lf$1$1.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lt.lk(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lb.ld(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lb.a(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lb$1.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l33f.lf$lI$1.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l68l.l1j.lI(Unknown Source)
	at com.groupdocs.conversion.internal.c.a.pd.internal.l68l.l1n.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by vsevolodorefin** [comment]
@xinbimingjingtai can you please share a sample file?

**Comment by xinbimingjingtai** [comment]
@vsevolodorefin I cannot add the attach file, but this is [download link](https://dlr1.fcdn.sk/books-files/_collection/userbooks/aa53383f75135d702ce589657d81f2c2385586ede3907b65d361e1c067c77ff8/redirection?filename=%E5%8F%A4%E9%BE%99%E5%85%A8%E9%9B%86%20%28%E5%8F%A4%E9%BE%99%29%20%28Z-Library%29.epub&md5=maiSbCHQKYMxXck-MazG4g&expires=1732189533), and this is [download page](https://z-lib.fm/book/6164554/c4e3ad/%E5%8F%A4%E9%BE%99%E5%85%A8%E9%9B%86.html)

**Comment by vsevolodorefin** [comment]
@xinbimingjingtai thank your for update, I will test it

**Comment by xinbimingjingtai** [comment]
@vsevolodorefin You can also try this [download page](https://z-lib.fm/book/6181224/8bbbdc/%E5%8F%A4%E9%BE%99%E4%BD%9C%E5%93%81%E5%85%A8%E9%9B%86%E7%B2%BE%E8%A3%8572%E5%86%8C.html), if the previous file cannot reproduce it.

**Comment by vsevolodorefin** [comment]
@xinbimingjingtai I reproduced and investigated the bug and assigned it to the responsive developer. I will update you when it is resolved.
